[REL-12052] Create org-wide labeler
tripactions/release-actions-workflows pull request #1
Opened 2023-05-10 09:57 UTC by Asemirski

2023-05-10 10:02 UTC, abystrov requested changes
You added only one part of the functionality to detect manual unlabeling, please use complete solution or remove it

2023-05-10 11:54 UTC, dkutluayta approved these changes

2023-05-10 11:54 UTC, dkutluayta approved these changes

2023-05-11 09:07 UTC, abystrov approved these changes

2023-05-11 09:28 UTC, dkutluayta approved these changes

2023-05-11 09:29 UTC, merged