REL-12496: Add workflow for dismissing approvals for DB PRs
tripactions/release-actions-workflows pull request #2
Opened 2023-06-06 12:53 UTC by dkutluayta

2023-06-06 12:55 UTC, Asemirski submitted a review, later dismissed

2023-06-06 13:13 UTC, abystrov requested changes

2023-06-06 13:13 UTC, abystrov commented on .github/workflows/dismiss-reviews.yml
> +      - name: Get PR number
Do we really need this step? You can simply use {{github.event.number}} in further steps

2023-06-06 13:36 UTC, dkutluayta commented on .github/workflows/dismiss-reviews.yml
> +      - name: Get PR number
Thanks for pointing this out. I couldn't find it when I first checked

2023-06-06 13:45 UTC, abystrov approved these changes

2023-06-07 13:39 UTC, uaflalo approved these changes

2023-06-07 13:54 UTC, merged